# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parse JSON String
#'
#' Takes a JSON string as input, returns a list of key-value pairs
#'
#' @param json const char, JSON string to be parsed. Coming from R, this
#'  input should be a character vector of length 1.
#' @export
from_json <- function(json) {
    .Call('_jsonparse_from_json', PACKAGE = 'jsonparse', json)
}

